version: '3'

services:
  postgres:
    image: postgres:latest
    ports:
      - '5434:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=scheduler
    volumes:
      - postgres-store:/var/lib/postgresql/data

volumes:
  postgres-store:
